redisHost: "localhost"
redisPort: 6379
redisPassword: "zaq1@WSX"

nearBorderTerrainModifyBlockDistance: 20

joinSectorOfflineMessage: "&cSektor na ktorym jestes jest offline"
outOfBorderMessage: "&cNie mozesz wyjsc poza border mapy!"
sectorOfflineMessage: "&cTen sektor jest offline"
nearBorderTerrainModifyMessage: "&cNie mozesz budowac 20 kratek od granicy sektora!"

nearBorderActionBar: "&c&lZblizasz sie do granicy mapy ({DISTANCE}m)"
nearSectorActionBar: "&cZblizasz sie do sektora {ID} ({DISTANCE}m) [{PERFORMANCE}] [{ONLINE} graczy]" # {PERFORMANCE} = "##.## TPS" || "OFFLINE"

sectors:
  first: # Server name from BungeeCord config
    min_x: -1000 # Min => inclusive
    max_x: 0 # Max => exclusive
    min_z: -1000
    max_z: 1000
    world: "world"
    default: true # Connect to default this sector on first join
  second:
    min_x: 0
    max_x: 1000
    min_z: -1000
    max_z: 1000
    world: "world"
    default: false

sectorsGui:
  guiName: "&c&lSectors status"
  online:
    material: WOOL
    amount: 1
    durability: 5
    name: "&a&l{ID} [ONLINE]"
    lore:
      - "&7TPS: &9{PERFORMANCE}"
      - "&7Online: &9{ONLINE}"
  offline:
    material: WOOL
    amount: 1
    durability: 14
    name: "&c&l{ID} [OFFLINE]"
    lore:
      - "&7Last online: &9{LAST_ONLINE}"