redisHost: "localhost"
redisPort: 6379
redisPassword: "zaq1@WSX"

nearBorderTerrainModifyBlockDistance: 20 ## How near border modifying terrain should be disallowed

joinSectorOfflineMessage: "&cYour sector is offline!" # Kick message for players that's trying to join, but are on offline sector
outOfBorderMessage: "&cYou can't go outside map's border!" # Message when player is trying to go outside map's border
sectorOfflineMessage: "&cThat sector is offline! You can't go there" # Message when player is trying to go to offline sector
nearBorderTerrainModifyMessage: "&cYou can modify terrain near border" # Message when player is trying to modify blocked terrain near border

nearBorderActionBar: "&c&lYou are approaching map border ({DISTANCE}m)" # ActionBar message near border
nearSectorActionBar: "&cYou are approaching sector {ID} ({DISTANCE}m) [{PERFORMANCE}] [{ONLINE} online]" # ActionBar message near another sector

sectors:
  first: # Server name from BungeeCord config
    min_x: -1000 # Min => inclusive
    max_x: 0 # Max => exclusive
    min_z: -1000
    max_z: 1000
    world: "world" # Sector's world
    default: true # Connect to default this sector on first join
  second:
    min_x: 0
    max_x: 1000
    min_z: -1000
    max_z: 1000
    world: "world"
    default: false

sectorsGui: # GUI with sectors' status
  guiName: "&c&lSectors status"
  online:
    material: WOOL
    amount: 1
    durability: 5
    name: "&a&l{ID} [ONLINE]"
    lore:
      - "&7TPS: &9{PERFORMANCE}"
      - "&7Online: &9{ONLINE}"
  offline:
    material: WOOL
    amount: 1
    durability: 14
    name: "&c&l{ID} [OFFLINE]"
    lore:
      - "&7Last online: &9{LAST_ONLINE}"