# CONFIG

sectors:
  first: # Server name from BungeeCord config
    min_x: -1000 # Min => inclusive
    max_x: 0 # Max => exclusive
    min_z: -1000
    max_z: 1000
    world: "world"
  second:
    min_x: 0
    max_x: 1000
    min_z: -1000
    max_z: 1000
    world: "world"